// src/scripts/seedSenadores.js
// Script para migrar los datos de senadores a MongoDB
// INCLUYE DATOS DE SUPLENTES

const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Senador = require('../models/Senador');

dotenv.config();

// ============================================
// FUNCIÓN PARA GENERAR SLUG
// ============================================
const generarSlug = (nombre) => {
  if (!nombre) return ''
  return nombre
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/ñ/g, 'n')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
}

// ============================================
// 🔥 DATA COMPLETA DE SENADORES (TITULARES + SUPLENTES)
// ============================================
const SENADORES_DATA = [
  // ============================================
  // SENADORES TITULARES (36)
  // ============================================
  { 
    id: 1, 
    seatNumber: 1, 
    name: "Wilder Véliz Armas", 
    slug: generarSlug("Wilder Véliz Armas"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Cochabamba",
    foto: "/senadores/titulares/g1/WILDER VELIZ ARMAS.png",
    suplente: "Lenny Mayra Ayala Justiniano",
    slugSuplente: generarSlug("Lenny Mayra Ayala Justiniano"),
    fotoSuplente: "/senadores/suplentes/g1/LENNY MAYRA AYALA JUSTINIANO.png",
    fechaNacimientoSuplente: "19 de enero, 1990",
    nacidoEnSuplente: "Cochabamba - Cercado - Cochabamba",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 2, 
    seatNumber: 2, 
    name: "Judith Rosario García Coca", 
    slug: generarSlug("Judith Rosario García Coca"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Potosí",
    foto: "/senadores/titulares/g1/JUDITH ROSARIO GARCIA COCA.png",
    suplente: "Royer Ivan Mamani Garcia",
    slugSuplente: generarSlug("Royer Ivan Mamani Garcia"),
    fotoSuplente: "/senadores/suplentes/g1/ROYER IVAN MAMANI GARCIA.png",
    fechaNacimientoSuplente: "15 de octubre, 1991",
    nacidoEnSuplente: "Cochabamba - Cercado - Cochabamba",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 3, 
    seatNumber: 3, 
    name: "Claudia Mallón Vargas", 
    slug: generarSlug("Claudia Mallón Vargas"),
    tipo: 'titular',
    party: "Autonomía para Bolivia Súmate", 
    partyShort: "APB", 
    partyColor: "#611789", 
    department: "Cochabamba",
    foto: "/senadores/titulares/g1/CLAUDIA MALLON VARGAS.png",
    suplente: "Apolinar Rivera Muñoz",
    slugSuplente: generarSlug("Apolinar Rivera Muñoz"),
    fotoSuplente: "/senadores/suplentes/g1/APOLINAR RIVERA MUÑOZ.png",
    fechaNacimientoSuplente: "3 de septiembre, 1966",
    nacidoEnSuplente: "Potosí - Tomas Frias - Potosí",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 4, 
    seatNumber: 4, 
    name: "Wanda Ximena Medrano Hervas", 
    slug: generarSlug("Wanda Ximena Medrano Hervas"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Cochabamba",
    foto: "/senadores/titulares/g1/WANDA XIMENA MEDRANO HERVAS.png",
    suplente: "Aldo Sergio Villegas Mora",
    slugSuplente: generarSlug("Aldo Sergio Villegas Mora"),
    fotoSuplente: "/senadores/suplentes/g1/ALDO SERGIO VILLEGAS MORA.png",
    fechaNacimientoSuplente: "20 de agosto, 1979",
    nacidoEnSuplente: "Oruro - Cercado - Oruro",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 5, 
    seatNumber: 5, 
    name: "José Manuel Ormachea Mendieta", 
    slug: generarSlug("José Manuel Ormachea Mendieta"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "La Paz",
    foto: "/senadores/titulares/g1/JOSE MANUEL ORMACHEA MENDIETA.png",
    suplente: "Maria Elena Pachacute Ticona",
    slugSuplente: generarSlug("Maria Elena Pachacute Ticona"),
    fotoSuplente: "/senadores/suplentes/g1/MARIA ELENA PACHACUTE TICONA.png",
    fechaNacimientoSuplente: "5 de febrero, 1990",
    nacidoEnSuplente: "La Paz - Murillo - Señora de La Paz",
    ocupacionSuplente: "Lic. en Comercio Internacional y Comunicación Social",
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: "https://www.facebook.com/share/1D8HNND7Ji/",
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: "https://www.tiktok.com/@elenapachacute?_r=1&_t=ZS-98rRgYCP1oz"
  },
  { 
    id: 6, 
    seatNumber: 6, 
    name: "Carmen Soledad Chapeton Tancara", 
    slug: generarSlug("Carmen Soledad Chapeton Tancara"),
    tipo: 'titular',
    party: "Unidad", 
    partyShort: "UNIDAD", 
    partyColor: "#EFCD04", 
    department: "La Paz",
    foto: "/senadores/titulares/g1/CARMEN SOLEDAD CHAPETÓN TANCARA.png",
    suplente: "Nilton Condori Alanoca",
    slugSuplente: generarSlug("Nilton Condori Alanoca"),
    fotoSuplente: "/senadores/suplentes/g1/NILTON CONDORI ALANOCA.png",
    fechaNacimientoSuplente: "12 de octubre, 1968",
    nacidoEnSuplente: "La Paz - Omasuyos - Tojocachi",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 7, 
    seatNumber: 7, 
    name: "Nicanor Gonzalo Cochi Condorí", 
    slug: generarSlug("Nicanor Gonzalo Cochi Condorí"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "La Paz",
    foto: "/senadores/titulares/g1/NICANOR GONZALO COCHI CONDORI.png",
    suplente: "Roxana Mamani Colquehuanca",
    slugSuplente: generarSlug("Roxana Mamani Colquehuanca"),
    fotoSuplente: "/senadores/suplentes/g1/ROXANA MAMANI COLQUEHUANCA.png",
    fechaNacimientoSuplente: "28 de septiembre, 1978",
    nacidoEnSuplente: "La Paz - Murillo - Señora de La Paz",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 8, 
    seatNumber: 8, 
    name: "Tomasa Yarhui Jacome", 
    slug: generarSlug("Tomasa Yarhui Jacome"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Chuquisaca",
    foto: "/senadores/titulares/g1/TOMASA YARHUI JACOME.png",
    suplente: "Hugo Marcelo Cortez Calvimontes",
    slugSuplente: generarSlug("Hugo Marcelo Cortez Calvimontes"),
    fotoSuplente: "/senadores/suplentes/g1/HUGO MARCELO CORTEZ CALVIMONTES.png",
    fechaNacimientoSuplente: "26 de enero, 1974",
    nacidoEnSuplente: "Chuquisaca - Oropeza - Sucre",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 9, 
    seatNumber: 9, 
    name: "Abdon Porcel Arancibia", 
    slug: generarSlug("Abdon Porcel Arancibia"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Chuquisaca",
    foto: "/senadores/titulares/g1/ABDON PORCEL ARANCIBIA.png",
    suplente: "Ilse Fatima Davila Arancibia",
    slugSuplente: generarSlug("Ilse Fatima Davila Arancibia"),
    fotoSuplente: "/senadores/suplentes/g1/ILSE FATIMA DAVILA ARANCIBIA.png",
    fechaNacimientoSuplente: "13 de mayo, 1984",
    nacidoEnSuplente: "Chuquisaca - Oropeza - Sucre",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 10, 
    seatNumber: 10, 
    name: "Bertha Cartagena Sánchez", 
    slug: generarSlug("Bertha Cartagena Sánchez"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Chuquisaca",
    foto: "/senadores/titulares/g1/BERTHA CARTAGENA SANCHEZ.png",
    suplente: "Manfred Leo Perez Hassenteufel",
    slugSuplente: generarSlug("Manfred Leo Perez Hassenteufel"),
    fotoSuplente: "/senadores/suplentes/g1/MANFRED LEO PEREZ HASSENTEUFEL.png",
    fechaNacimientoSuplente: "14 de noviembre, 1971",
    nacidoEnSuplente: "Chuquisaca - Luis Calvo - Muyupampa",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 11, 
    seatNumber: 11, 
    name: "Branko Goran Marinković Jovicevic", 
    slug: generarSlug("Branko Goran Marinković Jovicevic"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Santa Cruz",
    foto: "/senadores/titulares/g3/BRANKO GORAN MARINKOVIC JOVICEVIC.png",
    suplente: "Kathia Natalia Miserendino Romero",
    slugSuplente: generarSlug("Kathia Natalia Miserendino Romero"),
    fotoSuplente: "/senadores/suplentes/g3/KATHIA NATALIA MISERENDINO ROMERO.png",
    fechaNacimientoSuplente: "15 de diciembre, 1993",
    nacidoEnSuplente: "Santa Cruz - Andrés Ibáñez - Santa Cruz de la Sierra",
    ocupacionSuplente: "Ing. Agrónoma",
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: "https://www.facebook.com/katnat.miserendino",
    twitterSuplente: null,
    instagramSuplente: "https://www.instagram.com/senadoraporsantacruz/",
    youtubeSuplente: null,
    tiktokSuplente: "https://www.tiktok.com/@nataliamiserendino"
  },
  { 
    id: 12, 
    seatNumber: 12, 
    name: "Kathia Lizbeth Quiroga Fernández", 
    slug: generarSlug("Kathia Lizbeth Quiroga Fernández"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Santa Cruz",
    foto: "/senadores/titulares/g3/KATHIA LISBETH QUIROGA FERNÁNDEZ.png",
    suplente: "Leonardo Roca Eguez",
    slugSuplente: generarSlug("Leonardo Roca Eguez"),
    fotoSuplente: "/senadores/suplentes/g3/LEONARDO ROCA EGUEZ.png",
    fechaNacimientoSuplente: "4 de junio, 1980",
    nacidoEnSuplente: "Santa Cruz - Andres Ibañez - Santa Cruz de la Sierra",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 13, 
    seatNumber: 13, 
    name: "Rosa Tatiana Áñez Carrasco", 
    slug: generarSlug("Rosa Tatiana Áñez Carrasco"),
    tipo: 'titular',
    party: "Unidad", 
    partyShort: "UNIDAD", 
    partyColor: "#EFCD04", 
    department: "Santa Cruz",
    foto: "/senadores/titulares/g3/ROSA TATIANA AÑEZ CARRASCO.png",
    suplente: "Lorgio Fernando Pareja Saucedo",
    slugSuplente: generarSlug("Lorgio Fernando Pareja Saucedo"),
    fotoSuplente: "/senadores/suplentes/g3/LORGIO FERNANDO PAREJA SAUCEDO.png",
    fechaNacimientoSuplente: "6 de diciembre, 1985",
    nacidoEnSuplente: "Santa Cruz - Andrés Ibáñez - Santa Cruz de la Sierra",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 14, 
    seatNumber: 14, 
    name: "Paola Limbania López Zeballos", 
    slug: generarSlug("Paola Limbania López Zeballos"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Cochabamba",
    foto: "/senadores/titulares/g3/PAOLA LIMBANIA LOPEZ ZEBALLOS.png",
    suplente: "Richard Espada Ugarte",
    slugSuplente: generarSlug("Richard Espada Ugarte"),
    fotoSuplente: "/senadores/suplentes/g3/RICHARD ESPADA UGARTE.png",
    fechaNacimientoSuplente: "6 de febrero, 1986",
    nacidoEnSuplente: "Santa Cruz - Andrés Ibáñez - Santa Cruz de la Sierra",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 15, 
    seatNumber: 15, 
    name: "Betty Canaviri Villanueva", 
    slug: generarSlug("Betty Canaviri Villanueva"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Potosí",
    foto: "/senadores/titulares/g2/BETTY CANAVIRI VILLANUEVA.png",
    suplente: "Roger Mamani Coronado",
    slugSuplente: generarSlug("Roger Mamani Coronado"),
    fotoSuplente: "/senadores/suplentes/g2/ROGER MAMANI CORONADO.png",
    fechaNacimientoSuplente: "24 de junio, 1977",
    nacidoEnSuplente: "Potosí - Tomas Frias - Potosí",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 16, 
    seatNumber: 16, 
    name: "Teresa Alarcón Arana", 
    slug: generarSlug("Teresa Alarcón Arana"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Potosí",
    foto: "/senadores/titulares/g2/TERESA ALARCON ARANA.png",
    suplente: null,
    slugSuplente: null,
    fotoSuplente: null,
    fechaNacimientoSuplente: null,
    nacidoEnSuplente: null,
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 17, 
    seatNumber: 17, 
    name: "Marcelino Flores Ordoñez", 
    slug: generarSlug("Marcelino Flores Ordoñez"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Potosí",
    foto: "/senadores/titulares/g2/MARCELINO FLORES ORDOÑEZ.png",
    suplente: "Susana Gabriela Ruiz Zuleta",
    slugSuplente: generarSlug("Susana Gabriela Ruiz Zuleta"),
    fotoSuplente: "/senadores/suplentes/g2/SUSANA GABRIELA RUIZ ZULETA.png",
    fechaNacimientoSuplente: "12 de diciembre, 1984",
    nacidoEnSuplente: "Potosí - Tomas Frias - Potosí",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 18, 
    seatNumber: 18, 
    name: "Bertha Nurmy Gutiérrez Meneses", 
    slug: generarSlug("Bertha Nurmy Gutiérrez Meneses"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Potosí",
    foto: "/senadores/titulares/g2/BERTHA NURMY GUTIERREZ MENESES.png",
    suplente: "Freddy Rioja Melgar",
    slugSuplente: generarSlug("Freddy Rioja Melgar"),
    fotoSuplente: "/senadores/suplentes/g2/FREDDY RIOJA MELGAR.png",
    fechaNacimientoSuplente: "20 de abril, 1957",
    nacidoEnSuplente: "Santa Cruz - Cordillera - Camiri",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 19, 
    seatNumber: 19, 
    name: "Erick Nelson Soruco Alpire", 
    slug: generarSlug("Erick Nelson Soruco Alpire"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Beni",
    foto: "/senadores/titulares/g3/ERICK NELSON SORUCO ALPIRE.png",
    suplente: "Cesia Roca Escalante",
    slugSuplente: generarSlug("Cesia Roca Escalante"),
    fotoSuplente: "/senadores/suplentes/g3/CESIA ROCA ESCALANTE.png",
    fechaNacimientoSuplente: "30 de julio, 1971",
    nacidoEnSuplente: "Beni - Vaca Diez - Riberalta",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 20, 
    seatNumber: 20, 
    name: "José Roca Haensel", 
    slug: generarSlug("José Roca Haensel"),
    tipo: 'titular',
    party: "Unidad", 
    partyShort: "UNIDAD", 
    partyColor: "#EFCD04", 
    department: "Beni",
    foto: "/senadores/titulares/g3/JOSE ROCA HAENSEL.png",
    suplente: "Mabel Giordano Sonnenschein",
    slugSuplente: generarSlug("Mabel Giordano Sonnenschein"),
    fotoSuplente: "/senadores/suplentes/g3/MABEL GIORDANO SONNENSCHEIN.png",
    fechaNacimientoSuplente: "15 de enero, 1985",
    nacidoEnSuplente: "Beni - Vaca Diez - Riberalta",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 21, 
    seatNumber: 21, 
    name: "Ana Karina Velasco Añez", 
    slug: generarSlug("Ana Karina Velasco Añez"),
    tipo: 'titular',
    party: "Unidad", 
    partyShort: "UNIDAD", 
    partyColor: "#EFCD04", 
    department: "Beni",
    foto: "/senadores/titulares/g3/ANA KARINA VELASCO ÁÑEZ.png",
    suplente: "Marcelo Matias Cardona Ibañez",
    slugSuplente: generarSlug("Marcelo Matias Cardona Ibañez"),
    fotoSuplente: "/senadores/suplentes/g3/MARCELO MATIAS CARDONA IBAÑEZ.png",
    fechaNacimientoSuplente: "5 de enero, 1982",
    nacidoEnSuplente: "Cochabamba - Cercado - Cochabamba",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 22, 
    seatNumber: 22, 
    name: "Ernesto Suarez Sattori", 
    slug: generarSlug("Ernesto Suarez Sattori"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Cochabamba",
    foto: "/senadores/titulares/g3/ERNESTO SUAREZ SATTORI.png",
    suplente: "Claudia Cardenas Velasquez",
    slugSuplente: generarSlug("Claudia Cardenas Velasquez"),
    fotoSuplente: "/senadores/suplentes/g3/CLAUDIA CARDENAS VELASQUEZ.png",
    fechaNacimientoSuplente: "2 de julio, 1969",
    nacidoEnSuplente: "Cochabamba - Cercado - Cochabamba",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 23, 
    seatNumber: 23, 
    name: "Ana María Crispin Choque", 
    slug: generarSlug("Ana María Crispin Choque"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "La Paz",
    foto: "/senadores/titulares/g1/ANA MARIA CRISPIN CHOQUE.png",
    suplente: "Victor Severo Quispe Santander",
    slugSuplente: generarSlug("Victor Severo Quispe Santander"),
    fotoSuplente: "/senadores/suplentes/g1/VICTOR SEVERO QUISPE SANTANDER.png",
    fechaNacimientoSuplente: "1 de febrero, 1971",
    nacidoEnSuplente: "La Paz - Murillo - Nuestra Señora de La Paz",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 24, 
    seatNumber: 24, 
    name: "Julio Diego Romaña Galindo", 
    slug: generarSlug("Julio Diego Romaña Galindo"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Pando",
    foto: "/senadores/titulares/g3/JULIO DIEGO ROMAÑA GALINDO.png",
    suplente: "Carolina Giese Urresti",
    slugSuplente: generarSlug("Carolina Giese Urresti"),
    fotoSuplente: "/senadores/suplentes/g3/CAROLINA GIESE URRESTI.png",
    fechaNacimientoSuplente: "9 de noviembre, 1996",
    nacidoEnSuplente: "Pando - Nicolas Suarez - Cobija",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 25, 
    seatNumber: 25, 
    name: "Carol Carlo Durán", 
    slug: generarSlug("Carol Carlo Durán"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Pando",
    foto: "/senadores/titulares/g3/CAROL CARLO DURAN.png",
    suplente: "Jorge Antonio Quispe Flores",
    slugSuplente: generarSlug("Jorge Antonio Quispe Flores"),
    fotoSuplente: "/senadores/suplentes/g3/JORGE ANTONIO QUISPE FLORES.png",
    fechaNacimientoSuplente: "15 de enero, 1991",
    nacidoEnSuplente: "Pando - Nicolas Suarez - Cobija",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 26, 
    seatNumber: 26, 
    name: "Cintia Monica Puerta Campos", 
    slug: generarSlug("Cintia Monica Puerta Campos"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Pando",
    foto: "/senadores/titulares/g3/CINTIA MONICA PUERTA CAMPOS.png",
    suplente: "Jesus Humberto Suarez Eguez",
    slugSuplente: generarSlug("Jesus Humberto Suarez Eguez"),
    fotoSuplente: "/senadores/suplentes/g3/JESUS HUMBERTO SUAREZ EGUEZ.png",
    fechaNacimientoSuplente: "29 de mayo, 1980",
    nacidoEnSuplente: "Beni - Cercado - Trinidad",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 27, 
    seatNumber: 27, 
    name: "Eliana Rina Acosta Quispe", 
    slug: generarSlug("Eliana Rina Acosta Quispe"),
    tipo: 'titular',
    party: "Unidad", 
    partyShort: "UNIDAD", 
    partyColor: "#EFCD04", 
    department: "Cochabamba",
    foto: "/senadores/titulares/g3/ELIANA RINA ACOSTA QUISPE.png",
    suplente: "Sichard Hans Soraide Castedo",
    slugSuplente: generarSlug("Sichard Hans Soraide Castedo"),
    fotoSuplente: "/senadores/suplentes/g3/SICHARD HANS SORAIDE CASTEDO.png",
    fechaNacimientoSuplente: "28 de octubre, 1983",
    nacidoEnSuplente: "Santa Cruz - Andres Ibañez - Santa Cruz de la Sierra",
    ocupacionSuplente: "Ingeniero Informático",
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 28, 
    seatNumber: 28, 
    name: "Daniel Antonio Ortiz Velásquez", 
    slug: generarSlug("Daniel Antonio Ortiz Velásquez"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "La Paz",
    foto: "/senadores/titulares/g1/DANIEL ANTONIO ORTIZ VELASQUEZ.png",
    suplente: "Reina Isabel Pallares Morales",
    slugSuplente: generarSlug("Reina Isabel Pallares Morales"),
    fotoSuplente: "/senadores/suplentes/g1/REINA ISABEL PALLARES MORALES.png",
    fechaNacimientoSuplente: "16 de noviembre, 1963",
    nacidoEnSuplente: "Potosí - Chayanta - Ravelo",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 29, 
    seatNumber: 29, 
    name: "María Isabel Moreno Cortez", 
    slug: generarSlug("María Isabel Moreno Cortez"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Tarija",
    foto: "/senadores/titulares/g2/MARIA ISABEL MORENO CORTEZ.png",
    suplente: "Rolando Vacaflor Gabriel Arana",
    slugSuplente: generarSlug("Rolando Vacaflor Gabriel Arana"),
    fotoSuplente: "/senadores/suplentes/g2/ROLANDO VACAFLOR GABRIEL ARANA.png",
    fechaNacimientoSuplente: "18 de mayo, 1994",
    nacidoEnSuplente: "Tarija - Cercado - Tarija",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 30, 
    seatNumber: 30, 
    name: "César Mentasti Padilla", 
    slug: generarSlug("César Mentasti Padilla"),
    tipo: 'titular',
    party: "Unidad", 
    partyShort: "UNIDAD", 
    partyColor: "#EFCD04", 
    department: "Tarija",
    foto: "/senadores/titulares/g2/CESAR MENTASTI PADILLA.png",
    suplente: "Marcela Guerrero Vilca",
    slugSuplente: generarSlug("Marcela Guerrero Vilca"),
    fotoSuplente: "/senadores/suplentes/g2/MARCELA GUERRERO VILCA.png",
    fechaNacimientoSuplente: "10 de octubre, 1988",
    nacidoEnSuplente: "Tarija - Cercado - Tarija",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 31, 
    seatNumber: 31, 
    name: "Leonor Rosalva Romero Gutiérrez", 
    slug: generarSlug("Leonor Rosalva Romero Gutiérrez"),
    tipo: 'titular',
    party: "Unidad", 
    partyShort: "UNIDAD", 
    partyColor: "#EFCD04", 
    department: "Tarija",
    foto: "/senadores/titulares/g2/LEONOR ROSALVA ROMERO GUTIERREZ.png",
    suplente: "Marco Antonio Segovia Vargas",
    slugSuplente: generarSlug("Marco Antonio Segovia Vargas"),
    fotoSuplente: "/senadores/suplentes/g2/MARCO ANTONIO SEGOVIA VARGAS.png",
    fechaNacimientoSuplente: "30 de agosto, 1963",
    nacidoEnSuplente: "Tarija - Cercado - Tarija",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 32, 
    seatNumber: 32, 
    name: "Diego Esteban Mateo Ávila Navajas", 
    slug: generarSlug("Diego Esteban Mateo Ávila Navajas"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Tarija",
    foto: "/senadores/titulares/g2/DIEGO ESTEBAN MATEO ÁVILA NAVAJAS.png",
    suplente: "Luzmaya Zelaya Vega",
    slugSuplente: generarSlug("Luzmaya Zelaya Vega"),
    fotoSuplente: "/senadores/suplentes/g2/LUZMAYA ZELAYA VEGA.png",
    fechaNacimientoSuplente: "10 de febrero, 1987",
    nacidoEnSuplente: "Chuquisaca - Hernando Silez - San Pablo de Huacareta",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 33, 
    seatNumber: 33, 
    name: "Yasmín Estivariz Villarroel", 
    slug: generarSlug("Yasmín Estivariz Villarroel"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "Oruro",
    foto: "/senadores/titulares/g2/YASMIN ESTIVARIZ VILLARROEL.png",
    suplente: "Ramiro Mamani Ramirez",
    slugSuplente: generarSlug("Ramiro Mamani Ramirez"),
    fotoSuplente: "/senadores/suplentes/g2/RAMIRO MAMANI RAMIREZ.png",
    fechaNacimientoSuplente: "1 de agosto, 1990",
    nacidoEnSuplente: "Potosí - Alonso de Ibañez - Chojlla",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 34, 
    seatNumber: 34, 
    name: "Freddy Castillo Chávez", 
    slug: generarSlug("Freddy Castillo Chávez"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "La Paz",
    foto: "/senadores/titulares/g2/FREDDY CASTILLO CHAVEZ.png",
    suplente: "Villma Colque Camacho",
    slugSuplente: generarSlug("Villma Colque Camacho"),
    fotoSuplente: "/senadores/suplentes/g2/VILLMA COLQUE CAMACHO.png",
    fechaNacimientoSuplente: "10 de mayo, 1983",
    nacidoEnSuplente: "La Paz - Inquisivi - Choquetanga",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 35, 
    seatNumber: 35, 
    name: "Maria Antonieta Alcón Sánchez", 
    slug: generarSlug("Maria Antonieta Alcón Sánchez"),
    tipo: 'titular',
    party: "Partido Demócrata Cristiano", 
    partyShort: "PDC", 
    partyColor: "#2E7078", 
    department: "La Paz",
    foto: "/senadores/titulares/g2/MARIA ANTONIETA ALCON SANCHEZ.png",
    suplente: "Edwin Lopez Quiroga",
    slugSuplente: generarSlug("Edwin Lopez Quiroga"),
    fotoSuplente: "/senadores/suplentes/g2/EDWIN LOPEZ QUIROGA.png",
    fechaNacimientoSuplente: "14 de junio, 1957",
    nacidoEnSuplente: "Oruro - Cercado - Oruro",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  },
  { 
    id: 36, 
    seatNumber: 36, 
    name: "José Sánchez Aguilar", 
    slug: generarSlug("José Sánchez Aguilar"),
    tipo: 'titular',
    party: "Libre", 
    partyShort: "LIBRE", 
    partyColor: "#DB3737", 
    department: "Cochabamba",
    foto: "/senadores/titulares/g2/JOSE SANCHEZ AGUILAR.png",
    suplente: "Cinthya Inga Gutierrez Guzman",
    slugSuplente: generarSlug("Cinthya Inga Gutierrez Guzman"),
    fotoSuplente: "/senadores/suplentes/g2/CINTHYA INGA GUTIERREZ GUZMAN.png",
    fechaNacimientoSuplente: "15 de noviembre, 1981",
    nacidoEnSuplente: "Oruro - Cercado - Oruro",
    ocupacionSuplente: null,
    comiteSuplente: null,
    cargoSuplente: null,
    facebookSuplente: null,
    twitterSuplente: null,
    instagramSuplente: null,
    youtubeSuplente: null,
    tiktokSuplente: null
  }
];

// ============================================
// SCRIPT PRINCIPAL
// ============================================
async function seedSenadores() {
  console.log('\n' + '═'.repeat(80));
  console.log('👥 SEED DE SENADORES');
  console.log('   Migrando datos a MongoDB');
  console.log('   ✅ Incluye titulares y suplentes');
  console.log('═'.repeat(80) + '\n');

  try {
    console.log('🔌 Conectando a MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/senado_bolivia');
    console.log('✅ Conectado a MongoDB\n');

    const existingCount = await Senador.countDocuments();
    if (existingCount > 0) {
      console.log(`⚠️ Ya existen ${existingCount} senadores.`);
      const force = process.argv.includes('--force');
      if (!force) {
        console.log('   Usa --force para sobrescribir: node src/scripts/seedSenadores.js --force');
        process.exit(0);
      }
      console.log('🗑️ Eliminando senadores existentes...');
      await Senador.deleteMany({});
      console.log('✅ Eliminados\n');
    }

    console.log(`📝 Insertando ${SENADORES_DATA.length} senadores...\n`);
    
    const batchSize = 50;
    let inserted = 0;
    
    for (let i = 0; i < SENADORES_DATA.length; i += batchSize) {
      const batch = SENADORES_DATA.slice(i, i + batchSize);
      await Senador.insertMany(batch, { ordered: false });
      inserted += batch.length;
      console.log(`   ✅ Insertados ${inserted} de ${SENADORES_DATA.length}`);
    }

    console.log(`\n✅ ${inserted} senadores insertados exitosamente`);

    const total = await Senador.countDocuments();
    console.log(`\n📊 Total en base de datos: ${total} senadores`);

    const sample = await Senador.find().limit(5).lean();
    console.log('\n📋 Muestra de los primeros 5:');
    sample.forEach((s, i) => {
      console.log(`   ${i + 1}. ${s.name} (${s.partyShort}) - ${s.department}`);
      console.log(`      Suplente: ${s.suplente || 'Sin suplente'}`);
    });

    await mongoose.disconnect();
    console.log('\n' + '═'.repeat(80));
    console.log('🎉 SEED DE SENADORES COMPLETADO CON ÉXITO');
    console.log('   ✅ Titulares y suplentes migrados');
    console.log('═'.repeat(80) + '\n');

    process.exit(0);

  } catch (error) {
    console.error('\n❌ ERROR:', error.message);
    console.error(error.stack);
    await mongoose.disconnect().catch(() => {});
    process.exit(1);
  }
}

seedSenadores();